window.klaroConfig = {
  version: 1,
  elementID: 'klaro',
  styling: { theme: ['light'] },
  noAutoLoad: false,
  htmlTexts: true,
  embedded: false,
  cookieName: 'wildgewachsen-klaro',
  cookieExpiresAfterDays: 365,
  default: false,
  mustConsent: false,
  acceptAll: true,
  hideDeclineAll: false,
  hideLearnMore: false,
  noticeAsModal: false,
  translations: {
    de: {
      privacyPolicyUrl: '/impressum.html#datenschutz',
      consentNotice: {
        title: 'Cookies & Tracking',
        description: 'Wir setzen Cookies, um zu sehen, wenn du über unsere Affiliate-Links (Wise, SafetyWing, Booking, World Nomads) buchst. Dafür bekommen wir eine kleine Provision, du zahlst keinen Cent mehr. Du entscheidest.',
        learnMore: 'Mehr erfahren',
      },
      ok: 'Alle akzeptieren',
      decline: 'Ablehnen',
      acceptSelected: 'Auswahl speichern',
      consentModal: {
        title: 'Cookie-Einstellungen',
        description: 'Hier kannst du auswählen, welche Tracking-Dienste du erlaubst.',
      },
      purposes: {
        analytics: 'Reichweiten-Messung',
        affiliate: 'Affiliate-Tracking',
      },
    },
    en: {
      privacyPolicyUrl: '/en/privacy.html',
      consentNotice: {
        title: 'Cookies & Tracking',
        description: "We use cookies to see when you book through our affiliate links (Wise, SafetyWing, Booking, World Nomads). We get a small commission for that, you don't pay a cent more. You decide.",
        learnMore: 'Learn more',
      },
      ok: 'Accept all',
      decline: 'Decline',
      acceptSelected: 'Save selection',
      consentModal: {
        title: 'Cookie settings',
        description: 'Choose which tracking services you want to allow.',
      },
      purposes: {
        analytics: 'Audience measurement',
        affiliate: 'Affiliate tracking',
      },
    },
  },
  services: [
    {
      name: 'goatcounter',
      title: 'GoatCounter',
      purposes: ['analytics'],
      required: true,
      default: true,
      cookies: [],
      onlyOnce: true,
    },
    {
      name: 'wise',
      title: 'Wise',
      purposes: ['affiliate'],
      required: false,
      default: false,
      cookies: [/wise/],
    },
    {
      name: 'safetywing',
      title: 'SafetyWing',
      purposes: ['affiliate'],
      required: false,
      default: false,
      cookies: [/safetywing/, /sw_/],
    },
    {
      name: 'worldnomads',
      title: 'World Nomads',
      purposes: ['affiliate'],
      required: false,
      default: false,
      cookies: [/worldnomads/, /wn_/],
    },
    {
      name: 'booking',
      title: 'Booking.com',
      purposes: ['affiliate'],
      required: false,
      default: false,
      cookies: [/booking/, /aid=/],
    },
  ],
};
